const CONST = {
    DATA_PATH: '/data.json',
    TITLE_PLACEHOLDER: 'Title',
    NEWS_PLACEHOLDER: 'Your news',
    LOGIN: 'login',
    PASSWORD: 'password',
    WAIT: 'Please wait...',
    TEXT_TYPE: 'text',
    SUBMIT_TYPE: 'submit',
    LOGIN_PLACEHOLDER: 'Login',
    PASSWORD_PLACEHOLDER: 'Password',
    LOGIN_LABEL: 'login',
    PASSWORD_LABEL: 'password'
};

const CSS = {
    APP: 'app',
    CONTENT: 'content',
    ABOUT: 'about',
    ABOUT_TITLE: 'about__title',
    ABOUT_CONTENT: 'about__content',
    ADD: 'add',
    ADD_TITLE: 'add__title',
    ADD_NEWTITLE: 'add__new-title',
    ADD_NEWTEXT: 'add__new-text',
    ADD_SUBMIT: 'add__submit',
    ADMIN: 'admin',
    ADMIN_TITLE: 'admin__title',
    ADMIN_CONTENT: 'admin__content',
    CONTACTS: 'contacts',
    CONTACTS_TITLE: 'contacts__title',
    CONTACTS_CONTENT: 'contacts__content',
    ADDRESS: 'address',
    ADDRESS_TITLE: 'address__title',
    ADDRESS_CONTENT: 'address__content',
    PHONE: 'phone',
    PHONE_TITLE: 'phone__title',
    PHONE_LIST: 'phone__list',
    PHONE_ITEM: 'phone__item',
    EMAIL: 'email',
    EMAIL_TITLE: 'email__title',
    EMAIL_CONTENT: 'email__content',
    EDIT: 'edit',
    EDIT_TITLE: 'edit__title',
    EDIT_NEWTITLE: 'edit__new-title',
    EDIT_NEWTEXT: 'edit__new-text',
    EDIT_CONTROL: 'edit-control',
    EDIT_CONTROL_SUBMIT: 'edit-control__submit',
    EDIT_CONTROL_CANCEL: 'edit-control__cancel',
    ERROR404: 'error404',
    ERROR404_IMAGE: 'error404__image',
    ERROR404_INFO: 'error404__info',
    ERROR404_BACK: 'error404__back',
    ERROR404_LINK: 'error404__link',
    HEADER: 'header',
    HOME: 'home',
    HOME_TITLE: 'home__title',
    HOME_CONTENT: 'home__content',
    NAV: 'nav',
    MENU: 'menu',
    MENU_ITEM: 'menu-item',
    MENU_ITEM_LINK: 'menu-item__link',
    MENU_ITEM_LINK_ACTIVE: 'menu-item__link--active',
    MENU_ITEM_LINK_HIDDEN: 'menu-item__link--hidden',
    POST: 'post',
    POST_TITLE: 'post__title',
    POST_CONTENT: 'post__content',
    POST_FOOTER: 'post-footer',
    POST_FOOTER_DATE: 'post-footer__date',
    POST_FOOTER_EDIT: 'post-footer__edit',
    NEWS: 'news',
    NEWS_TITLE: 'news-title',
    NEWS_TITLE_TITLE: 'news-title__title',
    NEWS_TITLE_ADD_ACTIVE: 'news-title__add--active',
    NEWS_TITLE_ADD: 'news-title__add',
    NEWS_CONTENT: 'news__content',
    SIGN_FORM: 'sign-form',
    SIGN_FORM_LOGIN: 'sign-form__login',
    SIGN_FORM_PASSWORD: 'sign-form__password',
    SIGN_FORM_SUBMIT: 'sign-form__submit',
    SIGN_FORM_LOGIN_WRONG: 'sign-form__login--wrong',
    SIGN_FORM_PASSWORD_WRONG: 'sign-form__password--wrong',
    SIGN_FORM_LOGIN_BASE: 'sign-form__login--base',
    SIGN_FORM_PASSWORD_BASE: 'sign-form__password--base',
    ALERT_MESSAGE_VISIBLE: 'alert-message--visible',
    ALERT_MESSAGE_HIDDEN: 'alert-message--hidden'
};

export { CONST, CSS };