const CONST = {
    ENTER: 'Enter',
    KEYPRESS: 'keypress',
    FILTER_DEFAULT: 'all',
    LIST_CLASSNAME: 'list',
    PLACEHOLDER: 'ToDo',
    HEADER_CLASSNAME: 'header',
    INPUT_CLASSNAME: 'header__todo-input',
    CHECKBUTTON_BASE: 'header__check-button',
    CHECKBUTTON_VISIBLE: "header__check-button--visible",
    ALL_CHECKBUTTON_DONE: 'header__check-button--done',
    CHECKBUTTON_HIDDEN: 'header__check-button--hidden',
    EVENT_BLUR: 'blur',
    EVENT_ENTER: 'Enter',
    ALL_ID: 'all',
    ACTIVE_ID: 'active',
    COMPLETED_ID: 'completed',
    ITEM_CLASSNAME: 'item',
    ITEM_HIDDEN: 'item--hidden',
    CHECKBUTTON_CLASSNAME: 'item__check-button',
    CHECKBUTTON_DONE: "item__check-button--done",
    TITLE_CLASSNAME: 'item__todo-title',
    TITLE_DONE: 'item__todo-title--done',
    DELETE_BUTTON: 'item__delete-button',
    READONLY_ATTR: 'readonly',
    FOOTER_CLASSNAME: 'footer',
    FOOTER_HIDDEN: 'footer--hidden',
    COUNTER_CLASSNAME: 'footer__counter',
    BUTTON_CLASSNAME: 'footer-button',
    BUTTON_ACTIVE: 'footer-button--active',
    BUTTON_HIDDEN: 'footer-button--hidden',
    COMPLETED_DEFAULT: false,
};

export default CONST;
